<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
              <div class="row">
                <div class="col-sm-4">
                  <a id="logo" href="<?php echo BASE; ?>">
                      <img class="img-responsive" src="<?php echo IMG; ?>divvina-157x128.png" alt="" style="max-width:70px;">
                  </a> <br>
                </div>
                <div class="col-sm-8">
                  <span class="title-panel">DIVVINA BOUTIQUE</span>
                </div>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
              <?php echo (isset($this->alert) ? $this->alert :''); ?>
  
            </div>
        </div>
    </div>
</div>
