<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
              <div class="row">
                <div class="col-sm-4">
                  <a id="logo" href="<?php echo BASE; ?>">
                      <img class="img-responsive" src="<?php echo IMG; ?>divvina-157x128.png" alt="" style="max-width:70px;">
                  </a> <br>
                </div>
                <div class="col-sm-8">
                  <span class="title-panel">DIVVINA BOUTIQUE</span>
                </div>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
              <div class="alert alert-warning alert-block">
                <h4>Recupere sua senha.</h4>
                Um link de redefinição será enviado por e-mail. Por favor verifica a caixa de Spam.
              </div>
              <form class="form-horizontal">
        <div class="form-group">
          <label for="username" class="col-sm-3 control-label">Usuário:</label>
          <div class="col-sm-9">
            <input type="username" name="username" class="form-control" id="username" placeholder="usuario">
          </div>
        </div>


        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-10">
            <button type="submit" class="btn btn-primary">Enviar link de redefinição</button>
          </div>
        </div>
      </form>
            </div>
        </div>
    </div>
</div>
